# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 467)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(64, 69, 82);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pass_in = QtWidgets.QLineEdit(self.centralwidget)
        self.pass_in.setText("")
        self.pass_in.setClearButtonEnabled(False)
        self.pass_in.setObjectName("pass_in")
        self.gridLayout.addWidget(self.pass_in, 1, 2, 1, 1)
        self.id_in = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_in.sizePolicy().hasHeightForWidth())
        self.id_in.setSizePolicy(sizePolicy)
        self.id_in.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.id_in.setText("")
        self.id_in.setClearButtonEnabled(False)
        self.id_in.setObjectName("id_in")
        self.gridLayout.addWidget(self.id_in, 0, 2, 1, 1)
        self.pass_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pass_label.sizePolicy().hasHeightForWidth())
        self.pass_label.setSizePolicy(sizePolicy)
        self.pass_label.setObjectName("pass_label")
        self.gridLayout.addWidget(self.pass_label, 1, 0, 1, 2)
        self.course_in = QtWidgets.QLineEdit(self.centralwidget)
        self.course_in.setClearButtonEnabled(False)
        self.course_in.setObjectName("course_in")
        self.gridLayout.addWidget(self.course_in, 2, 2, 1, 1)
        self.course_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_label.sizePolicy().hasHeightForWidth())
        self.course_label.setSizePolicy(sizePolicy)
        self.course_label.setObjectName("course_label")
        self.gridLayout.addWidget(self.course_label, 2, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.semester_label = QtWidgets.QLabel(self.centralwidget)
        self.semester_label.setObjectName("semester_label")
        self.horizontalLayout_3.addWidget(self.semester_label)
        self.semester_in = QtWidgets.QComboBox(self.centralwidget)
        self.semester_in.setObjectName("semester_in")
        self.semester_in.addItem("")
        self.semester_in.addItem("")
        self.semester_in.addItem("")
        self.horizontalLayout_3.addWidget(self.semester_in)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frequency_label = QtWidgets.QLabel(self.centralwidget)
        self.frequency_label.setObjectName("frequency_label")
        self.horizontalLayout_4.addWidget(self.frequency_label)
        self.frequency_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.frequency_spin.setMinimum(60)
        self.frequency_spin.setMaximum(600)
        self.frequency_spin.setSingleStep(10)
        self.frequency_spin.setObjectName("frequency_spin")
        self.horizontalLayout_4.addWidget(self.frequency_spin)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 0, 1, 3)
        self.getGradesButton = QtWidgets.QPushButton(self.centralwidget)
        self.getGradesButton.setStyleSheet("background-color:rgb(47, 52, 63)")
        self.getGradesButton.setObjectName("getGradesButton")
        self.gridLayout.addWidget(self.getGradesButton, 6, 0, 1, 3)
        self.id_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_label.sizePolicy().hasHeightForWidth())
        self.id_label.setSizePolicy(sizePolicy)
        self.id_label.setObjectName("id_label")
        self.gridLayout.addWidget(self.id_label, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.year_label = QtWidgets.QLabel(self.centralwidget)
        self.year_label.setObjectName("year_label")
        self.horizontalLayout_2.addWidget(self.year_label)
        self.year_in = QtWidgets.QSpinBox(self.centralwidget)
        self.year_in.setMinimum(2015)
        self.year_in.setMaximum(2100)
        self.year_in.setProperty("value", 2018)
        self.year_in.setObjectName("year_in")
        self.horizontalLayout_2.addWidget(self.year_in)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.grades_table = QtWidgets.QTableWidget(self.centralwidget)
        self.grades_table.setGridStyle(QtCore.Qt.SolidLine)
        self.grades_table.setRowCount(0)
        self.grades_table.setColumnCount(0)
        self.grades_table.setObjectName("grades_table")
        self.grades_table.horizontalHeader().setVisible(False)
        self.grades_table.horizontalHeader().setStretchLastSection(True)
        self.grades_table.verticalHeader().setVisible(False)
        self.grades_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.grades_table, 1, 0, 1, 1)
        self.table_header = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_header.sizePolicy().hasHeightForWidth())
        self.table_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.table_header.setFont(font)
        self.table_header.setAlignment(QtCore.Qt.AlignCenter)
        self.table_header.setObjectName("table_header")
        self.gridLayout_3.addWidget(self.table_header, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gradesTrackerheader = QtWidgets.QLabel(self.centralwidget)
        self.gradesTrackerheader.setStyleSheet("font: 18pt \"Noto Sans\";\n"
"text-decoration: underline;")
        self.gradesTrackerheader.setObjectName("gradesTrackerheader")
        self.gridLayout_2.addWidget(self.gradesTrackerheader, 0, 0, 1, 1)
        self.disclaimer = QtWidgets.QLabel(self.centralwidget)
        self.disclaimer.setObjectName("disclaimer")
        self.gridLayout_2.addWidget(self.disclaimer, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setEnabled(False)
        self.start_button.setStyleSheet("background-color:rgb(47, 52, 63)")
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setEnabled(False)
        self.stop_button.setStyleSheet("background-color:rgb(47, 52, 63)")
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.course_in.returnPressed.connect(self.getGradesButton.click)
        self.pass_in.returnPressed.connect(self.getGradesButton.click)
        self.id_in.returnPressed.connect(self.getGradesButton.click)
        self.id_in.textChanged['QString'].connect(self.getGradesButton.toggle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.id_in, self.pass_in)
        MainWindow.setTabOrder(self.pass_in, self.course_in)
        MainWindow.setTabOrder(self.course_in, self.frequency_spin)
        MainWindow.setTabOrder(self.frequency_spin, self.getGradesButton)
        MainWindow.setTabOrder(self.getGradesButton, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.start_button)
        MainWindow.setTabOrder(self.start_button, self.stop_button)
        MainWindow.setTabOrder(self.stop_button, self.grades_table)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GradesTracker"))
        self.pass_in.setToolTip(_translate("MainWindow", "<html><head/><body><p>Technion account password</p></body></html>"))
        self.id_in.setToolTip(_translate("MainWindow", "<html><head/><body><p>Your cs account ID (without the @*)</p></body></html>"))
        self.pass_label.setText(_translate("MainWindow", "Password"))
        self.course_in.setToolTip(_translate("MainWindow", "<html><head/><body><p>Course number to track</p></body></html>"))
        self.course_label.setText(_translate("MainWindow", "Course Number"))
        self.semester_label.setText(_translate("MainWindow", "Semester"))
        self.semester_in.setItemText(0, _translate("MainWindow", "Winter"))
        self.semester_in.setItemText(1, _translate("MainWindow", "Spring"))
        self.semester_in.setItemText(2, _translate("MainWindow", "Summer"))
        self.frequency_label.setText(_translate("MainWindow", "Check Frequency(1/s)"))
        self.frequency_spin.setToolTip(_translate("MainWindow", "<html><head/><body><p>Check every * sec if there is new grade</p></body></html>"))
        self.getGradesButton.setText(_translate("MainWindow", "Get Grades"))
        self.id_label.setText(_translate("MainWindow", "ID"))
        self.year_label.setText(_translate("MainWindow", "Year"))
        self.table_header.setText(_translate("MainWindow", "Course Grades"))
        self.gradesTrackerheader.setText(_translate("MainWindow", "Grades Tracker:"))
        self.disclaimer.setText(_translate("MainWindow", "*(you must get the grades for the course first!)"))
        self.checkBox.setToolTip(_translate("MainWindow", "Sound will be played if new grades are found"))
        self.checkBox.setText(_translate("MainWindow", "Sound notification "))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))


