# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

import json

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        width, height = loadDimensions()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(width, height)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.grades_table = QtWidgets.QTableWidget(self.frame)
        self.grades_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grades_table.setStyleSheet("background-color: rgb(239, 240, 241);")
        self.grades_table.setGridStyle(QtCore.Qt.SolidLine)
        self.grades_table.setObjectName("grades_table")
        self.grades_table.setColumnCount(0)
        self.grades_table.setRowCount(0)
        self.grades_table.horizontalHeader().setVisible(False)
        self.grades_table.horizontalHeader().setStretchLastSection(True)
        self.grades_table.verticalHeader().setVisible(False)
        self.grades_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_6.addWidget(self.grades_table, 1, 0, 1, 1)
        self.table_header = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_header.sizePolicy().hasHeightForWidth())
        self.table_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.table_header.setFont(font)
        self.table_header.setStyleSheet("font: 12pt \"Noto Sans\";\n"
                                        "text-decoration: underline;")
        self.table_header.setAlignment(QtCore.Qt.AlignCenter)
        self.table_header.setObjectName("table_header")
        self.gridLayout_6.addWidget(self.table_header, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pass_in = QtWidgets.QLineEdit(self.frame)
        self.pass_in.setText("")
        self.pass_in.setClearButtonEnabled(False)
        self.pass_in.setObjectName("pass_in")
        self.gridLayout.addWidget(self.pass_in, 2, 3, 1, 2)
        self.id_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_label.sizePolicy().hasHeightForWidth())
        self.id_label.setSizePolicy(sizePolicy)
        self.id_label.setObjectName("id_label")
        self.gridLayout.addWidget(self.id_label, 1, 0, 1, 3)
        self.year_label = QtWidgets.QLabel(self.frame)
        self.year_label.setObjectName("year_label")
        self.gridLayout.addWidget(self.year_label, 4, 0, 1, 3)
        self.pass_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pass_label.sizePolicy().hasHeightForWidth())
        self.pass_label.setSizePolicy(sizePolicy)
        self.pass_label.setObjectName("pass_label")
        self.gridLayout.addWidget(self.pass_label, 2, 0, 1, 3)
        self.year_in = QtWidgets.QSpinBox(self.frame)
        self.year_in.setMinimum(2015)
        self.year_in.setMaximum(2100)
        self.year_in.setProperty("value", 2018)
        self.year_in.setObjectName("year_in")
        self.gridLayout.addWidget(self.year_in, 4, 3, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 5)
        self.frequency_spin = QtWidgets.QSpinBox(self.frame)
        self.frequency_spin.setMinimum(60)
        self.frequency_spin.setMaximum(600)
        self.frequency_spin.setSingleStep(10)
        self.frequency_spin.setObjectName("frequency_spin")
        self.gridLayout.addWidget(self.frequency_spin, 6, 3, 1, 2)
        self.getGradesButton = QtWidgets.QPushButton(self.frame)
        self.getGradesButton.setStyleSheet("")
        self.getGradesButton.setObjectName("getGradesButton")
        self.gridLayout.addWidget(self.getGradesButton, 7, 0, 1, 5)
        self.course_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_label.sizePolicy().hasHeightForWidth())
        self.course_label.setSizePolicy(sizePolicy)
        self.course_label.setObjectName("course_label")
        self.gridLayout.addWidget(self.course_label, 3, 0, 1, 3)
        self.semester_in = QtWidgets.QComboBox(self.frame)
        self.semester_in.setObjectName("semester_in")
        self.semester_in.addItem("")
        self.semester_in.addItem("")
        self.semester_in.addItem("")
        self.gridLayout.addWidget(self.semester_in, 5, 3, 1, 2)
        self.frequency_label = QtWidgets.QLabel(self.frame)
        self.frequency_label.setObjectName("frequency_label")
        self.gridLayout.addWidget(self.frequency_label, 6, 0, 1, 3)
        self.course_in = QtWidgets.QLineEdit(self.frame)
        self.course_in.setText("")
        self.course_in.setClearButtonEnabled(False)
        self.course_in.setObjectName("course_in")
        self.gridLayout.addWidget(self.course_in, 3, 3, 1, 2)
        self.id_in = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_in.sizePolicy().hasHeightForWidth())
        self.id_in.setSizePolicy(sizePolicy)
        self.id_in.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.id_in.setText(loadUserName())
        self.id_in.setClearButtonEnabled(False)
        self.id_in.setObjectName("id_in")
        self.gridLayout.addWidget(self.id_in, 1, 3, 1, 2)
        self.semester_label = QtWidgets.QLabel(self.frame)
        self.semester_label.setObjectName("semester_label")
        self.gridLayout.addWidget(self.semester_label, 5, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font: 12pt \"Noto Sans\";\n"
                                 "text-decoration: underline;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_button = QtWidgets.QPushButton(self.frame_3)
        self.start_button.setEnabled(False)
        self.start_button.setStyleSheet("")
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.frame_3)
        self.stop_button.setEnabled(False)
        self.stop_button.setStyleSheet("")
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.gridLayout_9.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.gradesTrackerheader = QtWidgets.QLabel(self.frame_3)
        self.gradesTrackerheader.setStyleSheet("font: 18pt \"Noto Sans\";\n"
                                               "text-decoration: underline;")
        self.gradesTrackerheader.setObjectName("gradesTrackerheader")
        self.gridLayout_9.addWidget(self.gradesTrackerheader, 1, 0, 1, 1)
        self.soundNotification = QtWidgets.QCheckBox(self.frame_3)
        self.soundNotification.setObjectName("soundNotification")
        self.gridLayout_9.addWidget(self.soundNotification, 2, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.grades_table.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.Stretch)
        self.grades_table.setLayoutDirection(QtCore.Qt.RightToLeft)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.id_in, self.pass_in)
        MainWindow.setTabOrder(self.pass_in, self.course_in)
        MainWindow.setTabOrder(self.course_in, self.year_in)
        MainWindow.setTabOrder(self.year_in, self.semester_in)
        MainWindow.setTabOrder(self.semester_in, self.frequency_spin)
        MainWindow.setTabOrder(self.frequency_spin, self.getGradesButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Course Tracker"))
        self.table_header.setText(_translate("MainWindow", "Grades Tracker"))
        self.pass_in.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Technion account password</p></body></html>"))
        self.id_label.setText(_translate("MainWindow", "ID"))
        self.year_label.setText(_translate("MainWindow", "Year"))
        self.pass_label.setText(_translate("MainWindow", "Password"))
        self.frequency_spin.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Check every * sec if there is new grade</p></body></html>"))
        self.getGradesButton.setText(_translate("MainWindow", "Get Grades"))
        self.course_label.setText(_translate("MainWindow", "Course Number"))
        self.semester_in.setItemText(0, _translate("MainWindow", "Winter"))
        self.semester_in.setItemText(1, _translate("MainWindow", "Spring"))
        self.semester_in.setItemText(2, _translate("MainWindow", "Summer"))
        self.frequency_label.setText(_translate("MainWindow", "Check Frequency(sec)"))
        self.course_in.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Course number to track</p></body></html>"))
        self.id_in.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Your cs account ID (without the @*)</p></body></html>"))
        self.semester_label.setText(_translate("MainWindow", "Semester"))
        self.label.setText(_translate("MainWindow", "User data:"))
        self.start_button.setToolTip(_translate("MainWindow",
                                                "<html><head/><body><p>You must get the grades for the course first!</p></body></html>"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.stop_button.setToolTip(_translate("MainWindow", "No tracker is running"))
        self.gradesTrackerheader.setText(_translate("MainWindow", "Course Tracker:"))
        self.soundNotification.setToolTip(_translate("MainWindow",
                                                     "<html><head/><body><p>Notify will be sounded when new grade is found</p></body></html>"))
        self.soundNotification.setText(_translate("MainWindow", "Sound notification "))


def loadDimensions():
    with open("settings.json", "r") as read_file:
        data = json.load(read_file)
        width = data['dimensions'][0]['width']
        height = data['dimensions'][0]['height']
        return width, height
    return 1320, 565


def loadUserName():
    with open("settings.json", "r") as read_file:
        data = json.load(read_file)
        return data['user_name']
    return ''
